# Required:
[[plugins]]
repo = 'Shougo/dein.vim'

# ステータスラインを好みの形式にカスタマイズする
[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'tpope/vim-fugitive'
hook_add = '''
"vim-fugitive
nnoremap <leader>ga :Git add %:p<CR><CR>
nnoremap <leader>gc :Git commit<CR><CR>
nnoremap <leader>gs :Git status<CR>
nnoremap <leader>gp :Git push<CR>
nnoremap <leader>gd :Git diff<CR>
nnoremap <leader>gl :Git log<CR>
nnoremap <leader>gb :Git blame<CR>
'''

# gc でコメントをトグルできる
[[plugins]]
repo = 'tomtom/tcomment_vim'
hook_add = '''
vnoremap ? :'<,'>TComment<CR>
'''
# カッコをカラフルにしてくれる
[[plugins]]
repo = 'luochen1990/rainbow'
hook_add = '''
    let g:rainbow_active=1
'''

[[plugins]]
repo = 'ryanoasis/vim-devicons'

# ctrl + Eでリサイズできる
[[plugins]]
repo = 'simeji/winresizer'

# fzf
[[plugins]]
repo = 'junegunn/fzf'
hook_post_update = './install --all'
merged = 0

# fzf.vim
[[plugins]]
repo = 'junegunn/fzf.vim'
depends = 'fzf'
hook_add = '''
    nnoremap <C-g> :Rg<Space>
    nnoremap <C-p> :GFiles<CR>
    nnoremap <C-h> :History
'''

# memo
[[plugins]]
repo = 'glidenote/memolist.vim'
hook_add = '''
    let g:memolist_path="$HOME/memo"
'''

