[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
# depends = [ 'nvim-yarp', 'vim-hug-neovim-rpc' ]
# enable if not using nvim

on_i = 1
hook_source = '''
let g:deoplete#enable_at_startup = 1
'''

[[plugins]]
repo = 'zchee/deoplete-clang'
hook_source = '''
let g:deoplete#sources#clang#libclang_path = '/usr/lib/llvm-6.0/lib/libclang-6.0.so.1'
let g:deoplete#sources#clang#clang_header = '/usr/include/clang'
'''
on_ft = ['c', 'cpp', 'cmake']
depends = ['deoplete.nvim']

[[plugins]]
repo = 'zchee/deoplete-jedi'
on_i = 1
on_ft = 'python'

[[plugins]]
repo = 'lervag/vimtex'
on_ft = ['tex']

[[plugins]]
repo = 'thinca/vim-quickrun'
hook_source = '''
let g:quickrun_config = {}
let g:quickrun_config['tex'] = {
    \ 'command' : 'latexmk',
    \ 'outputter' : 'error",
    \ 'outputter/error/error' : 'quickfix',
    \ 'cmdopt' : '-pdfdvi',
    \ 'exec' : ['%c % o %s']
    \}
'''
